#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/516bf5c8-7ab3-4956-ac59-abfd13200b8b # 
title: American Flights Api
version: 1.0

/flights:
 get:
  responses: 
    200:
      body: 
        application/json:
          example:  |
            [{"f_id": 1,"f_name": "ER38sd", "cost": 4000},
            {"f_id": 2,"f_name": "Mah4227", "cost": 5000},
            {"f_id": 3,"f_name": "mahiways", "cost": 5000},
            {"f_id": 4,"f_name": "xyz", "cost": 2000}
            ]


 post:
  body: 
    application/json:
      example:  |
        {"f_id": 3,"f_name": "mahiways", "cost": 4000}

  responses: 
    201:
      body: 
        application/json:
          example:  |
            {"message": "Flight added (but not really)"}
   
 /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              example:  |
                [ {"f_id": 2,"f_name": "Mah4227", "cost": 5000},
                  {"f_id": 3,"f_name": "mahiways", "cost": 5000}]




 

                  

  
       